---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAHDxMsMv89uvl41B0xyy141ItWDhbAsiKPtX3BKAcq+qEvZuGpZmgzjX1ZpL1VSgRjDmMOpR3b8ZAhgL6taM11e2su9IZHKxb8xFAInpICRI5g2E8nW4EMwyMp81YXIP/jkPwqOUekE72kIJ9RCDVT7l4n4RY8liEl1mMeLNVi7WSfhrhhX9E98Zlkr9ky2lGayuqiVWKwVEEgl7Tw1wdIPe7WNdACOTIybJsBnAaDW7ZFWWajOHK/yLdgLo1fYbGG9srSJ1ftAZUlKPWxa2EKEVi/Co0O6Yg78Ro+9NnUTNLe+R+XrdFc9JiC9q6hSp+ENxTPDkkMhK0LdrDP7i5W2cv1+wo7AZQyaTYVq1Vw7UYee0OkC7j95ycS6aeqCI1WrHRpUg+g9+p2g6H6NEBI7VlNX9FLBOB+l5JcvAn6q3tr2m0qMtAMOEAFmYeAeMC/OYlpmgjhmMg1I4psDPape4vtmxtBvLREKKEqbtJIBpeVYwu7cpMQlTWLZDMCYkSBuKDNV3bOR4YyxHzRPlCop1+xE0L4d3fQJqbGFCsKYrGVSgH6qCvv9B7RNUrjKnJyUM2CpBcFmZhCPRc+2PHxshVLjM8K6eQRzGnHsOcUmrqAvh8BqGuduQm2XgXrZrMIsI6TStkTRpDLPnzYdb14qhKsm+23mhbzGCWlBaXewVxia4iOT2ZgpCu29rC/91YM0b098nb9Utn9
    username: AgBpv3xRQJoGVVrvo8MDYNc2EudezZ5ZS+WbAKRFr2loTBjzHZsD27FZLRjbGhk6FiZ/jUFv2c/8HKe7H2WpOIW8kd8UYYlo4IyoU0v6v1rcRHY6XKmQgvkPFCNfBWXowkMOHnU+++sINprYKvLoWP2M9h8v0tOVbDy9G22BaZBHKJ2QkRrqc60DhPC3QamyxaqO2ha4eqCMSBxPLWAz62MW9W9+mBiW/nStyaqxHHJQIFm+WGy72lmqEPMXMj2rK2oFtSSkb94KQDTPmwPs1cQUTPcUotFwe4aW3ZDHSyiJkTm7nYd2qF1rbr/nVpdWxr95JNGPWmFYCuZG/2lWzxsjbnM/fceDrjcBewcfwBlCOWFZCILdg7oRK70W2yoA/GUyfhrNrUh21YktiuPte3QiC5DsAOU2q2rVn2MS0DP7bLwJzCVRJQPbuaOApCJtJ7lDcheYmeLe33E2EpRT0Hs1whQIJDq+jJMDUxfMwYVrkMbj4Xk0lgZFzz5vao4+Lj815K59+WDJAmtEYtCrgW0O37GpoDcrgdwB0qWM98ItufIkjkgOttPHR+AuhWJU3dKZUspGbL7BiLol++LopbHhTvftfbhMysaEbiXo4re4JYIpPrDqqYEzaZtsM1KUIwj6r8VXrAWYRtp0f8qmsn9f8mmYDdW9sIt/Ca97FytpKLCpfpch1Bz+yY3fWQY9EMn/rnYedw==
  template:
    metadata:
      name: secret-basic-auth
      namespace: default
    type: kubernetes.io/basic-auth
