---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-basic-auth
  namespace: default
spec:
  encryptedData:
    password: dummy
    username: dummy
    metadata:
      name: secret-basic-auth
      namespace: default
    type: kubernetes.io/basic-auth
