apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-deployment
  name: sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - image: myimage
        name: myimage
        resources: {}
status: {}
