apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "external-secret-azure-kv"
spec:
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  refreshPolicy: Periodic
  refreshInterval: "0h2m0s"
  target:
    name: application-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations: {}
        labels: {}
        finalizers: []
  data:
    - secretKey: username
      remoteRef:
        key: DBPASSWORDVISHNU
    - secretKey: password
      remoteRef:
        key: USERPASSWORD
        #version: v1
        #property: username
        #decodingStrategy: Base64 # can be None, Base64, Base64URL or Auto