---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dot-file-secret
  namespace: default
spec:
  encryptedData:
    .secret-file: dummy
  template:
    metadata:
      name: dot-file-secret
      namespace: default
