---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dot-file-secret
  namespace: default
spec:
  encryptedData:
    .secret-file: AgCLMy4S5OktXibHvqugJE0etlO1+3nRcb7SDaiqbp2G1bHxbyFN2nb4vw+A7Z0flTV1j+w1huwfdzvAKXJlRMVpfZ3Bwa1fIswPfXsaZ/FZgMiNPtBvzFZ9SiIfKFdAA6b/q/uyst54Pp2ecsu2UZCzAPwggQYOsPj2suth3hN8Yuo0bP/CcZhdmDs2HjG2tHDFAa5eWm7ehpF9FEhnlbNxyeY+7Z5ZewrI0nbXeklNaRIfVi4eUj9jpPqCLkXSKw1gNUiprm4Y+C8mbRdr59wOX0sZ50Q8GigF4y3NvwdspCWjuv2qIxr0V1obg4rPYZ1OJPQU0pyHH1woGpB0mBhzvAgLgLgFbnKd86X5j2p+g6uoI2DN6VSp6TjdRlGlH/OsYOiIfluFhtj7S2w8T4fN+H5JCjROrJuqzzestsWjeEKR7sX+yHKxzVkAcI8JQEdiVxyukDskKLUjhozPLe3sJuHyUUrWr0zC03Mgk4cesMiz3k9d4VMUYAf3lBVbGsbEb0wOKnSONVkP7O0KCl9N2Y6Q4fVZR3OhlU00QGxRaNo+9UeTxEY4VaJon7Nv+m16w9NTnHc0HxtnxyqtCNoqe6Luu0L8FLQLdiXYDO7pPg/mUgZNHme7UhHF6BbHBt5c0kk6g8ZNuiIL2QIIg+OlwJSQMHAqEOekUl29w9nTZmpe4s3CwygYl8mnoL1g5m5Kd29HnV7+OohCuw==
  template:
    metadata:
      name: dot-file-secret
      namespace: default
