apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-dotfiles-pod
  name: secret-dotfiles-pod-1
spec:
  volumes:
    - name: secret-dot-file
      secret:
        secretName: dot-file-secret
  containers:
  - image: busybox
    name: secret-dotfiles-pod
    command:
        - cat
        - "/etc/secret-volume/.secret-file"
    volumeMounts:
      - name: secret-dot-file
        readOnly: true
        mountPath: "/etc/secret-volume"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
