# This is a SecretProviderClass example using a service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-vishnukv001
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    userAssignedIdentityID: "false"
    keyvaultName: "vishnukv001"          # the name of the KeyVault 9a0786c7-f1d9-40ec-9bbe-2dcfff9c18d9
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DBPASSWORDVISHNU
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: "7bc11121-932a-4343-9dc9-7fa7fbbd8ca3"                 # the tenant ID of the KeyVault